-- MySQL Script generated by MySQL Workbench
-- Sat Sep 21 15:35:13 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`toures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`toures` (
  `idToures` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `desc` LONGTEXT NULL,
  `price` VARCHAR(45) NOT NULL,
  `startdate` DATE NOT NULL,
  `enddate` DATE NOT NULL,
  PRIMARY KEY (`idToures`),
  UNIQUE INDEX `idToures_UNIQUE` (`idToures` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`services` (
  `idservices` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `desc` LONGTEXT NULL,
  `price` VARCHAR(45) NULL,
  PRIMARY KEY (`idservices`),
  UNIQUE INDEX `idservices_UNIQUE` (`idservices` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`idusers`),
  UNIQUE INDEX `idusers_UNIQUE` (`idusers` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`operators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`operators` (
  `idoperators` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `raiting` INT NULL,
  PRIMARY KEY (`idoperators`),
  UNIQUE INDEX `idoperators_UNIQUE` (`idoperators` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `idorders` INT NOT NULL AUTO_INCREMENT,
  `service` INT NULL,
  `tour` INT NULL,
  `user` INT NULL,
  `operator` INT NULL,
  UNIQUE INDEX `idorders_UNIQUE` (`idorders` ASC) VISIBLE,
  PRIMARY KEY (`idorders`),
  INDEX `service_idx` (`service` ASC) VISIBLE,
  INDEX `tour_idx` (`tour` ASC) VISIBLE,
  INDEX `user_idx` (`user` ASC) VISIBLE,
  INDEX `operator_idx` (`operator` ASC) VISIBLE,
  CONSTRAINT `service`
    FOREIGN KEY (`service`)
    REFERENCES `mydb`.`services` (`idservices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tour`
    FOREIGN KEY (`tour`)
    REFERENCES `mydb`.`toures` (`idToures`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `operator`
    FOREIGN KEY (`operator`)
    REFERENCES `mydb`.`operators` (`idoperators`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
